---
title: "Disparities in Access to Capital"
format: html
toc: true
editor: visual
---

## Description

Today, we'll continue our conversation on the dynamics of homeownership in the United States, focusing on disparities in access to homeownership opportunities, and the implications of these disparities for the building and transfer of wealth.

## Learning Goals

-   Articulate some of the risks and rewards associated with owner-occupied housing.
-   Understand how access to capital and access to ownership opportunities has been used as a means of underscoring spatial segregation and inequality.

## Readings

Brookings Institution - *Examining the Black-White Wealth Gap* [{{< fa globe >}}](https://www.brookings.edu/articles/examining-the-black-white-wealth-gap/)

Keeyanga-Yamahtta Taylor - *How Real Estate Segregated America* [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/ysvbk93s48n8bb1p8ly91ns31gr529hi)

## Additional Resources

-   Council on Foreign Relations - *The U.S Inequality Debate* [{{< fa globe >}}](https://www.cfr.org/backgrounder/us-inequality-debate)

-   Investopedia - *What is the Racial Wealth Gap?* [{{< fa globe >}}](https://www.investopedia.com/the-racial-wealth-gap-5105010)

-   Homeownership, Racial Segregation and Policy Solutions to Racial Wealth Equity   [{{< fa arrow-up-right-from-square >}}]()   [{{< fa globe >}}](https://www.brookings.edu/articles/homeownership-racial-segregation-and-policies-for-racial-wealth-equity/)

-   Investor Home Purchases and the Rising Threat to Owners and Renters: Tales from 3 Cities [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/qj4ct4v5tumx08x484rxytatl31eqpon)

-   [How the Real Estate Boom Left Black Neighborhoods Behind - What Would it Take to Catch Up?  ](https://www.nytimes.com/2021/12/12/podcasts/the-daily/the-sunday-read-how-the-real-estate-boom-left-black-neighborhoods-behind.html)

-    [Should the Community Reinvestment Act Consider Race?](https://www.urban.org/sites/default/files/publication/105283/should-the-community-reinvestment-act-consider-race_1.pdf)

-    [Black Homeowners Face Discrimination in Appraisals](https://www.nytimes.com/2020/08/25/realestate/blacks-minorities-appraisals-discrimination.html)
