---
title: "Defining Affordable Housing"
format: html
toc: true
editor: visual
---

## Description

We often talk about housing being affordable, but what does affordable actually mean? In this session, we'll explore some of the various definitions for what affordability is and will question how those definitions might impact both policy making and policy implementation.

## Learning Goals

-   Become familiar with various definitions of housing affordability within the United States.
-   Understand how affordability relates to other key concepts including income and poverty.
-   Think critically about how affordability matters for housing consumption.

## Readings

Tilly, Chris - The Economic Environment of Housing: Income Inequality and Insecurity [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/x6zrr3q3h6f8lssvfocv366sn7oq4ou1)

Michael E. Stone - Housing Affordability: One-Third of a Nation Shelter-Poor [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/y87c02aelj78uvf9uzld472cqp1pb5ng)

Douglas on [Inclusionary Zoning](https://uofi.box.com/s/2n7f37j9iaf95n06a4lxhwd8c30pj3i5)

Crispin on TBD

## Questions for Reflection

1. In our past class sessions, we've contrasted two different models for banking - the Savings and Loan model and the "Modern" model which relies more heavily upon the selling of mortgages to shift loans off the bank's books. Thinking about these two models, identify the main sources of risks as well as which entities bear them. How can local policy help manage these risks?

2. What is the relationship between blight and housing stability? What types of management strategies can local governments use to address blight and housing stability at the same time?

3. Based upon the readings for today's class, how do you define residual income? How does residual income differ from other typical strategies for analyzing housing affordability?

## Additional Resources
