---
title: "Public Housing"
format: html
toc: true
editor: visual
---

## Description

In this session, we will explore the history and present reality of public housing in the United States. The public housing model has evolved significantly, especially over the last 20 years - we will track what physical, social, and economic phenomena led to this fundamental transformation, and will examine some of the policy debates regarding the potential future for public housing in the United States.

## Learning Goals

-   Understand the basic model for how Federal public housing programs work.
-   Articulate how the program has evolved over time, with a focus on the evolutionary forces that have shaped the program over the last 30 years.
-   Understand the role of public housing authorities play in owning and operating public housing, including some of the challenges they face in the current policy and economic environment.

## Readings

Schwartz 6

Smith, Janet, Public Housing Transformation: Evolving National Policy [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/qn0duv2naa2yo33a4r4j77fdv1o5md7f)

The Case for Truly Public Housing [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/kzh6wwws59rd9td17psnfg3wcnt4dclg)   [{{< fa globe >}}](https://placesjournal.org/article/the-case-for-truly-public-housing/?cn-reloaded=1)

Benson on TBD

## Questions for Reflection

1.  What are some of the tradeoffs associated with government ownership and operation of housing? What costs and risks does the state bear under this model?
2.  What narratives and imaginaries exist around public housing in the United States? How do these narratives shape policymaking? How do they impact tenants?
3.  Smith describes a wholesale transformation in public housing policy using Chicago as a case. What are the implications of this transformation for tenants? For the neighborhoods within which public housing is located?
4.  How might new visions for public housing akin to those which Schindler and Moyer describe reshape narratives of the meaning of public investment and operation of housing?

## Additional Resources

-   Reconsidering Public Housing in America ([link](https://beltmag.com/national-public-housing-museum-reconsidering-public-housing-america/))

-   [Greenlee, Lee, and McNamara, Performance of Small Public Housing Authorities: Opportunities and Barriers](https://www.jstor.org/stable/26524883?seq=1#metadata_info_tab_contents)
