---
title: "Housing Market Discrimination"
format: html
toc: true
editor: visual
---

## Description

In our previous unit, we explored several elements of fair housing enforcement. This session will tie together those prior conversations with additional insights on housing market discrimination.

## Learning Goals

-   Understand more about how individual and structural biases within the housing system drive certain populations to experience higher rates of housing market discrimination.

-   Understand how advocates work to develop evidence that will help to counteract discrimination when it is observed.

## Readings

Schwartz 11

Last Week Tonight - Housing Discrimination

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/_-0J49_9lwc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

Choi, Ann, Bill Dedman, Keither Herbert, and Olivia Winslow - Long Island Divided [{{< fa globe >}}](https://projects.newsday.com/long-island/real-estate-agents-investigation/)

Rothstein, Richard, The Color of Law (Chapter 12)   [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/khatcjenuvejf9ens8gy4jvx1sst94jg)

## Slides

## Additional Resources

-   New York Times - Selling Houses While Black

-    [Disparate Impact and Fair Housing: Seven Cases You Should Know](https://www.propublica.org/article/disparate-impact-and-fair-housing-seven-cases-you-should-know)

-    [Can you Game Your Way out of American Housing Injustice?](https://www.bloomberg.com/news/articles/2022-01-12/video-game-spotlights-racism-in-u-s-housing-system?srnd=citylab-housing) / [STEAM link](https://store.steampowered.com/app/1763520/Dots_Home/)

-    [Housing Segregation in Everything](https://www.npr.org/sections/codeswitch/2018/04/11/601494521/video-housing-segregation-in-everything)

<iframe width="100%" height="290" src="https://www.npr.org/player/embed/601131468/601396049" frameborder="0">

</iframe>

https://youtu.be/O5FBJyqfoLM
