---
title: "Schedule"
format: html
toc: false
editor: visual
---

Our course schedule is subject to change over the course of semester - please check here often for updates.

## How will we learn together? How can we conceptualize the impacts of housing and urban policy?

+-----------+-----------------------------------------------------------------+
| **Date**  | **Topic**                                                       |
+-----------+-----------------------------------------------------------------+
| 8/26/2025 | [Course Introduction](01_introduction.qmd)                      |
+-----------+-----------------------------------------------------------------+
| 8/28/2025 | [Conceptual Frameworks for Housing Analysis](02_conceptual.qmd) |
+-----------+-----------------------------------------------------------------+
| 9/2/2025  | [How well are we housed?](03_housed.qmd)                        |
|           |                                                                 |
|           | (Class Via Zoom)                                                |
+-----------+-----------------------------------------------------------------+
| 9/4/2025  | [Government intervention in housing](04_government.qmd)         |
|           |                                                                 |
|           | (Class Via Zoom)                                                |
+-----------+-----------------------------------------------------------------+
| 9/9/2025  | [Reading Week - No Class Session](05_readingwk.qmd)             |
+-----------+-----------------------------------------------------------------+
| 9/11/2025 | [Reading Week - No Class Session](05_readingwk.qmd)             |
+-----------+-----------------------------------------------------------------+

## How do we Ensure Housing Stability?

| Date | Topic |
|----|----|
| 9/16/2025 | [An Evolutionary History of Homeownership 1](07_homeownership.qmd) |
| 9/18/2025 | [An Evolutionary History of Homeownership 2](08_homeownership2.qmd) |
| 9/23/2025 | [Disparities in Access to Capital](09_homeownership3) |
| 9/25/2025 | [The Enduring Significance of Neighborhoods](10_neighborhoods.qmd) |

## Where are poor people to live? What housing are poor people to occupy?

|           |                                                            |
|-----------|------------------------------------------------------------|
| **Date**  | **Topic**                                                  |
| 9/30/2025 | [Defining Affordable Housing](11_affordable.qmd)           |
| 10/2/2025 | [Public Housing](12_publichousing.qmd)                     |
| 10/7/2025 | [Housing Vouchers](13_fedassisted.qmd)                     |
| 10/9/2025 | [Federal Housing Production Strategies](14_production.qmd) |

## How do we Ensure Fairness in Housing?

|            |                                                         |
|------------|---------------------------------------------------------|
| **Date**   | **Topic**                                               |
| 10/14/2025 | [Legal Frameworks for Fair Housing](15_fairhousing.qmd) |
| 10/16/2025 | No Class - Housing Action Illinois Conference           |
| 10/21/2025 | No Class - ACSP Conference                              |
| 10/23/2025 | No Class - ACSP Conference                              |
| 10/28/2025 | [Eviction](19_eviction.qmd)                             |
| 10/30/2025 | [Code Enforcement](20_hsgenv.qmd)                       |

## How do we Address the Housing Needs of Specialized Populations?

|            |                                                        |
|------------|--------------------------------------------------------|
| **Date**   | **Topic**                                              |
| 11/4/2025  | [Housing Market Discrimination](21_discrimination.qmd) |
| 11/6/2025  | [Aging](22_aging.qmd)                                  |
| 11/11/2025 | [Disability](23_disability.qmd)                        |
| 11/13/2025 | [Houselessness](24_houselessness.qmd)                  |
| 11/18/2025 | [Housing and Health](25_health.qmd)                    |
| 11/20/2025 | No Class - Independent Work Day                        |

## What's your plan for intervention?

| Date       | Topic                                       |
|------------|---------------------------------------------|
| 11/25/2025 | [No Class - Fall Break](27_break.qmd)       |
| 11/27/2025 | [No Class - Fall Break](28_break.qmd)       |
| 12/2/2025  | [Final Presentations](29_presentations.qmd) |
| 12/4/2025  | [Final Presentations](30_presentations.qmd) |
| 12/9/2025  | [Final Presentations](31_presentations.qmd) |
