---
title: "Term Paper"
format: html
toc: false
editor: visual
---

Doctoral students in UP 473 will produce a term-length paper on a topic of your choice that draws upon the academic literature to engage with a theme related to housing policy. Based upon your interests and goals for the class, this paper could include original empirical analysis of a phenomenon, could be theory-based, or could be focused on synthesizing literature. We will work together to determine an appropriate paper scope and approach. In addition to preparing your term assignment, you will present your paper to the class at the end of the semester.

Your completed term paper will be due at the end of the semester. In order to ensure that you are making adequate progress to meet this deadline, you will submit several intermediate work products including the following:

| Assignment | Description | Length | Submit Via | Due Date |
|---------------|---------------|---------------|---------------|---------------|
| Term Paper Proposal | Proposal summarizing your term project | 2 pages | Canvas | 9/8/2025 |
| Extended Abstract and Paper Outline | Extended abstract of approximately 300 words that describes your paper's topic and approach. A paper outline with top-level section narrative descriptions should follow. | 3 - 5 pages | Canvas | 10/6/2025 |
| Literature Review | Literature review narrative covering around sources that provides contextual scoping and framing for your paper. | 5-6 pages | Canvas | 11/10/2025 |
| Presentation | Final presentation in class | 20 minutes plus time for questions | Canvas | 12/8/2025 |
| Term Paper | Final term paper suitable for review and publication in a journal of your choice. | Between 8,000 and 10,000 words (excluding references) | Canvas | 12/15/2025 |
